version: '3'
services:
  recipebook_db:
    image: mysql:latest
    env_file:
     - ./.env_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    restart: "no"
    networks:
      - mynetwork
  recipebook_api:
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - .env_db
    ports:
      - 127.0.0.1:8000:8000
    restart: "no"
    depends_on:
      - recipebook_db
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/recipes || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  recipebook_webapp:
    build:
     context: webapp
     dockerfile: Dockerfile
    env_file:
      - .env_db
    ports:
     - 127.0.0.1:3223:3223
    restart: "no"
    volumes:
      - ./jwt_keys:/app/jwt_keys:ro
    depends_on:
      - recipebook_api
      - recipebook_db
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3223/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  recipebook_nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      # - ./frontend/static:/etc/nginx/html/static
      - ./favicon.ico:/app/favicon.ico:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      recipebook_api:
        condition: service_healthy
      recipebook_webapp:
        condition: service_healthy
    networks:
      - mynetwork

networks:
  mynetwork:
