version: '3'
services:
  recipebook_api:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env_db
    ports:
      - 127.0.0.1:8000:8000
    restart: on-failure
    depends_on:
      - recipebook_db
    networks:
      - mynetwork
  recipebook_webapp:
    build:
     context: frontend
     dockerfile: Dockerfile
    env_file:
      - .env_db
    ports:
     - 127.0.0.1:3223:3223
    restart: on-failure
    depends_on:
      - recipebook_api
      - recipebook_db
    networks:
      - mynetwork
  recipebook_nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - recipebook_api
      - recipebook_webapp
    networks:
      - mynetwork
  recipebook_db:
    image: mysql:latest
    env_file:
     - ./.env_db
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
